### ISSUE TITLE
No Juniper Support

### ISSUE THREAD

**Issue by ghost** [tbotnz/netpalm-flask-hello-arp-world#1]
We cannot let this crime go unpunished.

**Comment by tbotnz** [comment]
Would add but i domt have a juniper lab yet :(

**Comment by tbotnz** [comment]
Junipers have no soul @packetferret

**Comment by ghost** [comment]
Junipervitus lives on

**Comment by tbotnz** [comment]
Automation with junos is just too easy. Theres been API since like 1940
